server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://192.168.72.134:3306/local?useUnicode=true&characterEncoding=utf8
    username: root
    password: Jia_@1995
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.72.134
    port: 6379
    password: #密码默认为空
    jedis:
      pool:
        max-active: 8 #使用负数表示没有限制
        max-wait: -1 #使用负数表示没有限制
        max-idle: 8 #连接池最大空闲链接
        min-idle: 0 #连接池最小空闲链接
    timeout: 30000 #链接超时时间（毫秒）
  rabbitmq:
    host: 192.168.72.134
    port: 15672
    username: guest
    password: guest
mybatis-plus:
  mapper-locations: classpath:com/boot/base/mapper/xml/*.xml
  type-aliases-package: com/boot/base/entity
  configuration:
    map-underscore-to-camel-case: true
